export const GET_ALL_CATEGORY_DETAILS_REQUEST = 'GET_ALL_CATEGORY_DETAILS_REQUEST';
export const GET_ALL_CATEGORY_DETAILS_SUCCESS = 'GET_ALL_CATEGORY_DETAILS_SUCCESS';
export const GET_ALL_CATEGORY_DETAILS_FAILURE = 'GET_ALL_CATEGORY_DETAILS_FAILURE';

export const GET_DETAIL_BY_CATE_REQUEST = 'GET_DETAIL_BY_CATE_REQUEST';
export const GET_DETAIL_BY_CATE_SUCCESS = 'GET_DETAIL_BY_CATE_SUCCESS';
export const GET_DETAIL_BY_CATE_FAILURE = 'GET_DETAIL_BY_CATE_FAILURE';